### ISSUE TITLE
Easy conversion of content packages into Maven projects

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-eclipse-developer-tools#49]
It should be possible to easily convert or import a content package into a content project.

**Comment by Omnipresent** [comment]
Absolutely! I'm in a position where I have access to the package from package manager but not the source from eclipse ( with pom.xml). I want to add additional features to this package and reverse engineering a pom.xml is not trivial. 

Happy to contribute towards making this happen

**Comment by rombert** [comment]
@Omnipresent - sorry, I missed this comment earlier. It's great that you're willing to contribute towards this feature! I currently don't have an idea on exactly how this can be implemented, so feel free to start with some suggestions. We can then find a way to plug these in the WTP framework.

**Comment by VasiRahman** [comment]
> It should be possible to easily convert or import a content package into a content project.

Hi gabrielwalt,

Is it possible if yes? What are the steps needs to follow?

**Comment by gabrielwalt** [comment]
Closing this as we won't have the bandwidth to work on that in the next months, sorry @VasiRahman.
