### ISSUE TITLE
failing to auto deploy bundles - SocketTimeout

### ISSUE THREAD

**Issue by kmurugulla** [adobe/aem-eclipse-developer-tools#52]
Eclipse - 4.4.1
AEM Developer Tools - 1.0.4
Sling IDE Tools - 1.0.6
Sling IDE Tools,M2e-based -1.0.6
Java - 1.7.0_67
Mac OSX 10.10.3
AEM Server setting : 
"Publish -->Automatically Publish when resource changes" with publishing interval of 5 secs.
and "Install --> Install bundle directly from filesystem""

Issue on auto deploying bundles -
Failed installing bundle : java.net.SocketTimeoutException: Read timed out
java.net.SocketTimeoutException: Read timed out

note : restarting aem instance fixes the issue though . But wondering whether its some thing specific to aem tools or connectivity between aem and eclipse it self ?
Any ideas ?

**Comment by rombert** [comment]
Is your AEM instance running on localhost? If it is, does the port it uses (4502 I assume) match the one configured for the server in Eclipse?

**Comment by kmurugulla** [comment]
Yes , my aem is on local instance 4502 and it matches the aem server config in eclipse .

**Comment by rombert** [comment]
Is it possible that the deployment of that bundle takes a long time? Do you have anything related to its deployment in `crx-quickstart/logs/error.log`?

**Comment by gabrielwalt** [comment]
Closing this as there hasn't been activity for over a year.
