### ISSUE TITLE
Remove AEM Nature not available

### ISSUE THREAD

**Issue by ashlyjose** [adobe/aem-eclipse-developer-tools#54]
If a project is configured as a Content Project (by mistake), there should an option to remove the AEM nature from the project

**Comment by eglistefan** [comment]
good idea!
ps: meanwhile this can be achieved manually by modifying the nature section in the .project file.

**Comment by rombert** [comment]
@ashlyjose - converting to a content/bundle project does two things

- adds the faceted project nature
- adds a content/bundle facet

The facets can be removed by right-clicking on the project, selecting project facets, unchecking the particular facet you want to remove and pressing OK.

I'm not sure if it's possible to remove the faceted nature, but that's out of scope for us

**Comment by ashlyjose** [comment]
Thanks @rombert - it works.

It is possible to remove the faceted nature as Maven plugin does it. You have the option in Maven to remove maven nature

**Comment by rombert** [comment]
By "out of scope for us" I mean to say that the faceted nature is something we inherit from the other Eclipse projects and we should not try to remove it.

**Comment by gabrielwalt** [comment]
Closing this as there hasn't been activity for over a year.
