### ISSUE TITLE
/rep:policy node for the root node does not get imported

### ISSUE THREAD

**Issue by chetanyajain** [adobe/aem-eclipse-developer-tools#74]
While running the command Import from server using eclipse it doesn't import the rep:policy that is present at the root level i.e. filter-vlt.xml containing <filter root="/rep:policy" />.

Observed this issue with Eclipse Neon.

**Comment by rombert** [comment]
Users and ACLs don't get imported, see also https://issues.apache.org/jira/browse/SLING-3827 . For me personally this is not on the roadmap yet as ACLs are not imported/changed that often, at least when compared to scripts and unstructured content.

**Comment by chetanyajain** [comment]
The ACLs for other levels are getting imported. Only the one at the root level has issues - per the logs it iterates through the node, just that the file _rep_policy.xml doesn't get created.

**Comment by rombert** [comment]
Ah, you're right, sorry. I misread that as ACLs are not exported. Yes, sounds like a bug.

**Comment by gabrielwalt** [comment]
Closing this as there hasn't been activity for over a year.
