### ISSUE TITLE
Export ignores filter.xml

### ISSUE THREAD

**Issue by ofuangka** [adobe/aem-eclipse-developer-tools#76]
I've exported /libs/foundation to jcr_root to get my JSPs to validate, but even though my filter.xml does not include /libs/foundation, the plugin fails to export:

Could not publish to the server.
Resource at path /libs/foundation/components/form/defaults/field is not a direct child of /libs/foundation/components/form/defaults/items

**Comment by rombert** [comment]
Can you share a project which reproduces this problem? I can't fix the issue without reproducing.

**Comment by ofuangka** [comment]
Unfortunately I can't share my source, but the problem seems to have to do with config.xml when it contains the following:

`<aggregate type="full" title="Full Coverage Aggregate">
            <matches>
                <include nodeType="rep:AccessControl" respectSupertype="true" />
                <include nodeType="cq:Widget" respectSupertype="true" />
                <include nodeType="cq:WidgetCollection" respectSupertype="true" />
                <include nodeType="cq:EditConfig" respectSupertype="true" />
                <include nodeType="cq:WorkflowModel" respectSupertype="true" />
                <include nodeType="vlt:FullCoverage" respectSupertype="true" />
                <include nodeType="mix:language" respectSupertype="true" />
                <include nodeType="sling:OsgiConfig" respectSupertype="true" />
            </matches>
        </aggregate>`

instead of

`
        <aggregate type="full" title="Full Coverage Aggregate">
            <matches>
                <include nodeType="rep:AccessControl" respectSupertype="true" />
                <include nodeType="rep:Policy" respectSupertype="true" />
                <include nodeType="cq:Widget" respectSupertype="true" />
                <include nodeType="cq:EditConfig" respectSupertype="true" />
                <include nodeType="cq:WorkflowModel" respectSupertype="true" />
                <include nodeType="vlt:FullCoverage" respectSupertype="true" />
                <include nodeType="mix:language" respectSupertype="true" />
                <include nodeType="sling:OsgiConfig" respectSupertype="true" />
            </matches>
        </aggregate>
`

**Comment by ofuangka** [comment]
Basically you should be able to create a dummy content-package project with a filter.xml and a filter-vlt.xml that contains `<filter root="/libs/foundation"/>` and a config.xml that contains the first snippet above. Then run `vlt export http://localhost:4502 .` in the content folder. For some reason that changes the contents of filter.xml, so you have to then remove `<filter root="/libs/foundation"/>` from it. Then try to publish the project using the plugin.

**Comment by gabrielwalt** [comment]
Closing this as there hasn't been activity for over a year.
