### ISSUE TITLE
Repo root is not detected in archetype 19

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-eclipse-developer-tools#85]
With the change in [1] to the aem-maven-archetype the repo root is not detect anymore in the plugin.

![image (2)](https://user-images.githubusercontent.com/689884/62038582-4b01ef80-b1f6-11e9-9c31-0618f075818e.png)

[1] https://github.com/adobe/aem-project-archetype/commit/20cf62ba0e8ad466f31973d8cc2c45df37c15c87

**Comment by jeremytrpka-perficient** [comment]
I've noticed it works from version 17 and lower. I am getting the same issue with version 18 where it only recognizes "src/main/resources" instead of "src/main/content".

**Comment by kwin** [comment]
This should be fixed by https://issues.apache.org/jira/browse/SLING-9117.
